### ISSUE TITLE
use android native channel for acinq lib verification of bip340 signatures

### ISSUE THREAD

**Issue by frnandu** [0xchat-app/nostr-dart#2]
...since it's ~10x faster than standard dart bip340.
We use it on https://github.com/frnandu/yana
I can help implement it if you want.
Let me know.
Currently 0xchat is extremely slow (specially when cold start of app) on a galaxy s20 phone.
Similarily yana was like this before switching to use acinq native android lib

**Comment by water783** [comment]
> ...since it's ~10x faster than standard dart bip340. We use it on https://github.com/frnandu/yana I can help implement it if you want. Let me know. Currently 0xchat is extremely slow (specially when cold start of app) on a galaxy s20 phone. Similarily yana was like this before switching to use acinq native android lib

That's great, I think I really need it!

**Comment by water783** [comment]
fixed in the latest version
